version: "3.8"
services:
  postgres-db:
    container_name: devorders
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: devorders
      POSTGRES_PASSWORD: devorders
      POSTGRES_DB: devorders
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5437:5432"

volumes:
  postgresql_data:
    driver: local
