spring:
  application:
    name: devorders

  datasource:
    url: jdbc:postgresql://localhost:5437/devorders
    driver-class-name: org.postgresql.Driver
    username: devorders
    password: devorders
  flyway:
    enabled: true
    locations: classpath:db/migration
    jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none
  server:
    port: 8080
