CREATE TABLE step
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    step_complete BOOLEAN,
    CONSTRAINT pk_step PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description   VARCHAR(255)                            NOT NULL,
    task_complete BOOLEAN,
    task_fk       BIGINT,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_TASK_FK FOREIGN KEY (task_fk) REFERENCES step (id);