CREATE TABLE subtask
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description      VARCHAR(255)                            NOT NULL,
    subtask_complete BOOLEAN,
    step_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_subtask PRIMARY KEY (id)
);

ALTER TABLE subtask
    ADD CONSTRAINT FK_SUBTASK_ON_STEP FOREIGN KEY (step_id) REFERENCES step (id);